storage: Fix racy makedirs
Under some odd circumstances this code was causing a stack trace in
production like:

   FileExistsError: [Errno 17] File exists: '/data/ci_jobs/zephyr-upstream/958/lava-96b_nitrogen'

        at makedirs (/usr/lib/python3.5/os.py:241)
        at console_logfd (/srv/jobserv/jobserv/storage/base.py:70)
        at run_update (/srv/jobserv/jobserv/api/run.py:171)

Signed-off-by: Andy Doan <andy.doan@linaro.org>