runner: Fix flaky reboot issue
We are seeing sporadic errors with Runs doing reboots:

 ERROR:jobserv-worker:Last call exited with rc: 1
 WARNING:jobserv-worker:Found rebooted-run, preparing to execute
 Traceback (most recent call last):
   File "/srv/jobserv-worker/jobserv_worker.py", line 524, in <module>
     main(get_args())
   File "/srv/jobserv-worker/jobserv_worker.py", line 474, in main
     args.func(args)
   File "/srv/jobserv-worker/jobserv_worker.py", line 377, in cmd_check
     if _handle_rebooted_run(args.server):
   File "/srv/jobserv-worker/jobserv_worker.py", line 364, in _handle_rebooted_run
     os.rename(reboot_run, rundir)
 OSError: [Errno 39] Directory not empty: '/srv/jobserv-worker/rebooted-run' -> '/srv/jobserv-worker/runs/rebooted-run'

I think we have to be careful about flushing changes to disk before
we call a reboot on a device.

Signed-off-by: Andy Doan <andy@opensourcefoundries.com>